name: Deploy Flask with ngrok

on:
  push:
    branches:
      - main

permissions:
  contents: write  # اجازه نوشتن در ریپو برای اکشن

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Update timestamp
        run: |
          echo "$(cat app.py) " > app.py

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add app.py
          git commit -m "first commit"
          git push
        
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} 