name: Deploy Flask with ngrok

on:
  schedule:
    - cron: '0 */6 * * *'  # هر 6 ساعت یک بار
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Update timestamp
        run: |
          echo "# Updated at $(date)" >> app.py

      - name: Commit and push changes if any
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add app.py
          git diff --cached --quiet || git commit -m "Auto update timestamp"
          git push
