name: Deploy Flask with ngrok

on:
  workflow_dispatch:
    types: [trigger-from-first-workflow]
  push:
    branches:
      - main

permissions:
  contents: write  # اجازه نوشتن در ریپو برای اکشن

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Update timestamp
        run: |
          echo "$(cat app.py) " > app.py

      - name: Commit and push changes
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.yml/dispatches \
          -d '{"ref":"main"}'